server:
  port: 8081


spring:
  datasource:
    name: seckill
    url: jdbc:mysql://101.43.189.45:3306/mybaits-demo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER